# Generated by Django 5.2.7 on 2025-11-03 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ModEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('cargo', models.CharField(choices=[('Líder técnico', 'Líder técnico'), ('Desarrollador senior', 'Desarrollador senior'), ('Desarrollador junior', 'Desarrollador junior'), ('Tester QA', 'Tester QA'), ('Admin. de servidores/BD', 'Admin. de servidores/BD'), ('Diseñador UX/UI', 'Diseñador UX/UI'), ('Especialista en seguridad', 'Especialista en seguridad'), ('Analista funcional', 'Analista funcional')], max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('cerrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('ACT', 'Activo'), ('PAS', 'Pasivo'), ('CAP', 'Capital'), ('ING', 'Ingreso'), ('GAS', 'Gasto')], max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('haber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('automatica', models.BooleanField(default=False)),
                ('cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SIC.cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='BalanceComprobacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debe', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('haber', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIC.cuenta')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIC.periodo')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('Debe', 'Debe'), ('Haber', 'Haber')], max_length=5)),
                ('exento_iva', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIC.cuenta')),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SIC.periodo')),
            ],
        ),
    ]
