# Generated by Django 5.2.7 on 2025-10-25 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('ACT', 'Activo'), ('PAS', 'Pasivo'), ('CAP', 'Capital'), ('ING', 'Ingreso'), ('GAS', 'Gasto')], max_length=50)),
                ('nombre', models.CharField(max_length=100)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('haber', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SIC.cuenta')),
            ],
        ),
    ]
