# Generated by Django 4.2.25 on 2025-10-28 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SIC', '0002_alter_cuenta_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('Debe', 'Debe'), ('Haber', 'Haber')], max_length=5)),
                ('exento_iva', models.BooleanField(default=False)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SIC.cuenta')),
            ],
        ),
    ]
