# Generated by Django 5.2.7 on 2025-11-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIC', '0003_transaccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(editable=False, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
