# Generated by Django 5.2.7 on 2025-11-02 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIC', '0003_periodocontable_transaccion_movimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimiento',
            name='cuenta',
        ),
        migrations.RemoveField(
            model_name='movimiento',
            name='transaccion',
        ),
        migrations.DeleteModel(
            name='PeriodoContable',
        ),
        migrations.DeleteModel(
            name='Movimiento',
        ),
    ]
