# Generated by Django 5.2.7 on 2025-11-02 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIC', '0005_periodo_transaccion_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
