# Generated by Django 5.2.7 on 2025-11-02 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIC', '0005_modempleado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cif',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='modempleado',
            name='codigo',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
    ]
