# Generated by Django 5.2.7 on 2025-11-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIC', '0007_balancecomprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='automatica',
            field=models.BooleanField(default=False),
        ),
    ]
