# Generated by Django 5.2.7 on 2025-11-07 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIC', '0008_cuenta_automatica'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notas', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ModEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('cargo', models.CharField(choices=[('Líder técnico', 'Líder técnico'), ('Desarrollador senior', 'Desarrollador senior'), ('Desarrollador junior', 'Desarrollador junior'), ('Tester QA', 'Tester QA'), ('Admin. de servidores/BD', 'Admin. de servidores/BD'), ('Diseñador UX/UI', 'Diseñador UX/UI'), ('Especialista en seguridad', 'Especialista en seguridad'), ('Analista funcional', 'Analista funcional')], max_length=50)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
