# Generated by Django 5.2.7 on 2025-11-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIC', '0009_cif_modempleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='modempleado',
            name='aguinaldo',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12),
            preserve_default=False,
        ),
    ]
