# Generated by Django 5.2.7 on 2025-11-10 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SIC', '0010_modempleado_aguinaldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modempleado',
            name='aguinaldo',
        ),
    ]
