# Generated by Django 5.2.7 on 2025-11-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIC', '0011_remove_modempleado_aguinaldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
