# Generated by Django 5.2.7 on 2025-11-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIC', '0012_alter_periodo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
